config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :index, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5)}, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:chef, :show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end


  def top
    @restaurants = Restaurant.where(stars: 5)
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

    def chef
    @chef_name = @restaurant.chef_name
  end

    def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def update
    @restaurant.update(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
    redirect_to restaurant_path(@restaurant)
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    # 1. get data from form
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    # 2. Set the restaurant to the review
    @review.restaurant_id = @restaurant.id
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @review.update(review_params)
    id = @review.restaurant_id
    if @review.save
      redirect_to restaurant_path(id)
    else
      render :edit
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="UTF-8">
</head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<% form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :phone_number %>
<%= f.text_field :phone_number %>
<%= f.label :category %>
<%= f.text_field :category %>
<% end %>

app/views/restaurants/_navbar_wagon.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>Edit <%= @restaurant.name %>:</h1>
    </div>
    <div class="col-xs-6 col-xs-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
<h1>List of all the restaurants</h1>
  <div class="row margin-top-list">
    <div class="col-xs-12">
      <ul>
        <% @restaurants.each do |restaurant| %>
        <li class="display-list card-shadow banner-card">
          <div class="margin-left-card">
            <h3 class="no-margin-top">
              <%= link_to restaurant.name, restaurant_path(restaurant) %>
            </h3>
            <div>
              <%= restaurant.address %>
            </div>
            <div>
              <%= restaurant.phone_number %>
            </div>
            <div>
              <%= restaurant.category.capitalize %>
            </div>
          </div>
          <div class="btn-margin-right"> <!-- description -->
            <%= link_to "See Reviews", restaurant_reviews_path(restaurant), class:"btn btn-primary" %>
            <%= link_to "Edit Restaurant", edit_restaurant_path(restaurant), class:"btn btn-warning" %>
            <%= link_to "Delete Restaurant", restaurant_path(restaurant), method: :delete, data: {confirm: "Are you sure to delete #{restaurant.name}"},class:"btn btn-danger" %>
          </div> <!-- /description -->

        </li>
        <% end %>
      </ul>
    </div>
  </div>
     <%= link_to "Add a new restaurant", new_restaurant_path, class:"btn btn-success mybtnclass" %>
   </div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
<h1><%= @restaurant.name %></h1>
  <div class="row margin-top-list">
    <div class="col-xs-12">
      <div class="display-list card-shadow banner-card">
        <div class="margin-left-card">
          <div>
            <b>Address:</b> <%= @restaurant.address %>
          </div>
          <div>
            <b>Phone Number: </b><%= @restaurant.phone_number %>
          </div>
          <div>
            <b>Category: </b><%= @restaurant.category.capitalize %>
          </div>
        </div>
        <div class="btn-margin-right"> <!-- description -->
          <%= link_to "Restaurant review", restaurant_reviews_path(@restaurant), class:"btn btn-primary" %>
          <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), class:"btn btn-warning" %>
          <%= link_to "Delete Restaurant", restaurant_path(@restaurant), method: :delete, data: {confirm: "Are you sure to delete #{@restaurant.name}"},class:"btn btn-danger" %>
        </div> <!-- /description -->
      </div>
      <h3 class="text-center">Reviews</h3>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <% @restaurant.reviews.each do |review| %>
          <li class="display-list card-shadow">
            <div class="card-review">
              <h3 class="no-margin-top">
                <%= "*" * review.rating%>
              </h3>
              <p>
                <%= review.content %>
              </p>
            </div>
            <div class="btn-margin-right"> <!-- description -->
              <%= link_to "Edit Review", edit_review_path(review), class:"btn btn-warning" %>
              <%= link_to "Delete Review", review_path(review), method: :delete, data: {confirm: "Are you sure to delete this review"},class:"btn btn-danger" %>
            </div> <!-- /description -->
          </li>
          <% end %>
        </div>
      </div>
      <%= link_to "Add a new Review", new_restaurant_review_path(@restaurant), class:"btn btn-success mybtnclass" %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.input :rating %>
<%= f.input :content %>
<%= f.submit class:"btn btn-success mybtnclass"%>

<% end %>

app/views/reviews/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>Edit a review</h1>
    </div>
    <div class="col-xs-6 col-xs-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container">
<h1>List of all the reviews for <%= @restaurant.name %></h1>
  <div class="row margin-top-list">
    <div class="col-xs-12">
      <ul>
        <% @restaurant.reviews.each do |review| %>
        <li class="display-list card-shadow banner-card">
          <div class="margin-left-card ">
            <h3 class="no-margin-top">
              <%= "*" * review.rating%>
            </h3>
            <div class="card-review">
              <%= review.content %>
            </div>
          </div>
          <div class="btn-margin-right"> <!-- description -->
            <%= link_to "Back to restaurant details", restaurant_path(@restaurant), class:"btn btn-primary" %>
            <%= link_to "Edit Review", edit_review_path(review), class:"btn btn-warning" %>
            <%= link_to "Delete Review", review_path(review), method: :delete, data: {confirm: "Are you sure to delete this review"},class:"btn btn-danger" %>
          </div> <!-- /description -->

        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to "Add a new review", new_restaurant_review_path, class:"btn btn-success mybtnclass" %>
</div>

app/views/reviews/new.html.erb
<h1>Reviews for <%= @restaurant.name %></h1>

<!-- <form action=""> -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "submit review", class: "btn btn-primary" %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>Add a new review</h1>
    </div>
    <div class="col-xs-6 col-xs-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>